### ISSUE TITLE
1XBet?

### ISSUE THREAD

**Issue by imurreflection** [jimtape/new#2]
Hi, could there b a particular reason for using 1xBet only when original HD prints are available elsewhere. Since only scraping is used for finding links, can we please try to locate non 1XBet links.

**Comment by hydroxd** [comment]
1xbet is a betting site and seems to be a sponsor for this app as it only contains 1xbet ads in its enitirety, 1xbet is the reason the app is still running so, yeah we have no choice but to see those ads, i hope this clarifies🙏👍

**Comment by imurreflection** [comment]
It's not about ads my friend..that's perfectly alright..What i am asking is about quality of the print. However, it appears that they are improving as can be seen in form of a new player with better quality options in 79 update
